services:
  backend-db:
    image: postgres:17.0-bookworm
    container_name: stunning-autumn-foliage_backend-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data:
